enquiries/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

wl/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('enquiries.urls')),
]

enquiries/models.py
from datetime import timedelta, date

from django.db import models
from django.utils import timezone

# Create your models here.
class Enquiry(models.Model):
    # Set default date to today + delta days
    def defaultDate(delta):
        return timezone.now() + timedelta(days=delta)

    name = models.CharField(
        max_length=50,
    )
    email = models.EmailField(
        max_length=80,
    )
    adults = models.SmallIntegerField(
        default=1,
    )
    children = models.SmallIntegerField(
        default=0,
    )
    enq_date_start = models.DateField(
        default=defaultDate(1),
    )
    enq_date_end = models.DateField(
        default=defaultDate(8),
    )
    sent_time = models.DateTimeField(
        auto_now_add=True,
    )

    def __str__(self):
        return '%s, %s' % (self.name, self.email)

enquiries/forms.py
from datetime import timedelta, date

from django import forms
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError

from . import validators

class EnquiryForm(forms.Form):
    choices_adult = ((1, '1'), (2, '2'))
    choices_children = ((0, '0'), (1, '1'), (2, '2'))

    name = forms.CharField(
        label='Name',
        max_length=50,
        validators=[validators.validate_alpha],
    )
    email = forms.EmailField(
        label='Email address',
        max_length=80,
        validators=[validators.validate_email],
    )
    enq_date_start = forms.DateField(
        label='Check-in date',
        widget=forms.DateInput(attrs={'class': 'datepicker'}),
        validators=[validators.validate_future],
    )
    enq_date_end = forms.DateField(
        label='Check-out date',
        widget=forms.DateInput(attrs={'class': 'datepicker'}),
    )
    adults = forms.ChoiceField(
        choices=choices_adult,
        validators=[validators.validate_integer],
    )
    children = forms.ChoiceField(
        choices=choices_children,
        validators=[validators.validate_integer],
    )

    def clean(self):
        cleaned_data = super().clean()
        enq_date_start = cleaned_data.get('enq_date_start')
        enq_date_end = cleaned_data.get('enq_date_end')

        """Check that check-out is at least 2 days after check-in"""
        if enq_date_start and enq_date_end:
            error_text = "Check-out date must be at least 2 days after check-in date"
            if enq_date_start - enq_date_end >= timedelta(days=-1):
                self.add_error('enq_date_end', error_text)

enquiries/views.py
import os
import ssl
import sendgrid
from sendgrid.helpers.mail import *

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail
from django.utils import timezone

from .forms import EnquiryForm
from .models import Enquiry

# ssl._create_default_https_context = ssl._create_unverified_context

# Create your views here.
def index(request):
    if request.method == 'POST':
        form = EnquiryForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            e = Enquiry(
                name = data['name'],
                email = data['email'],
                adults = data['adults'],
                children = data['children'],
                enq_date_start = data['enq_date_start'],
                enq_date_end = data['enq_date_end'],
            )
            e.save()
            # Compile the email
            subject = 'New Enquiry from your Website'
            message = ('You have received a new enquiry on your website. '
            + 'Here are the details:\n\n'
            + 'From: ' + e.name + '\n'
            + 'Email: ' + e.email + '\n'
            + str(e.adults) + ' adults' + '\n'
            + str(e.children) + ' children' + '\n'
            + 'Check-in: ' + e.enq_date_start.strftime('%d %B, %Y') + '\n'
            + 'Check-out: ' + e.enq_date_end.strftime('%d %B, %Y') + '\n'
            )
            # send_mail(
            #     subject,
            #     message,
            #     'jar3dh0lm3s@gmail.com',
            #     ['wisterialodge11@gmail.com'],
            #     fail_silently=True,
            # )
            # return render(request, 'enquiries/dist/enquiry-success.html', {'form': form})
            sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
            from_email = Email('wisterialodge11@gmail.com')
            to_email = Email('wisterialodge11@gmail.com')
            email_subject = subject
            email_content = Content('text/plain', message)
            mail = Mail(from_email, email_subject, to_email, email_content)
            response = sg.client.mail.send.post(request_body=mail.get())

            if response.status_code == 202:
                return render(request, 'enquiries/dist/enquiry-success.html', context = { 'form' : form })

    else:
        form = EnquiryForm()

    context = {
        'form': form
    }

    return render(request, 'enquiries/dist/enquiry.html', context,)

enquiries/templates/enquiries/src/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-118022197-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-118022197-1');
  </script>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% block meta-description %}
  <meta name="description" content="Wisteria Lodge is a cosy yet sophisticated cottage in North-West Johannesburg, South Africa.">
  {% endblock %}

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'enquiries/dist/stylesheets/wl-styles.css' %}">

  {% block extra-links %}
  {% endblock %}
  <title>{% block title %}{% endblock %} | Wisteria Lodge</title>
</head>
<body>
  <nav>
    <div class="nav-wrapper tan">
      <a href="http://wisterialodge.co.za/" class="brand-logo center cursive">Wisteria Lodge</a>
      <a href="#" class="sidenav-trigger" data-target="nav-mobile"><i class="fas fa-ellipsis-v"></i></a>
      <ul class="right hide-on-med-and-down">

        {% block nav-which-active %}
        <li><a href="http://wisterialodge.co.za/" class="nav-active">Home</a></li>
        <li><a href="http://wisterialodge.co.za/enquire">Enquire</a></li>
        <li><a href="http://wisterialodge.co.za/contact.html">Contact Us</a></li>
        {% endblock %}

      </ul>
      <ul class="sidenav" id="nav-mobile">

        {% block sidenav-which-active %}
        <li><a href="http://wisterialodge.co.za/" class="nav-active">Home</a></li>
        <li><a href="http://wisterialodge.co.za/enquire">Enquire</a></li>
        <li><a href="http://wisterialodge.co.za/contact.html">Contact Us</a></li>
        {% endblock %}

      </ul>
    </div>
  </nav>

  <main>
    {% block main %}
    {% endblock %}
  </main>

  <footer class="grey lighten-3" id="footer">
    {% block footer %}
    <div class="footer-copyright">
      <div class="container">
        <div class="row">
          <div class="col s6 left">
            <h2 class="footer-link hwd"><a href="http://www.jaredholmes.com/" class="teal-text text-darken-2" target="_blank">Web design by Holmes Web Development</a></h2>
          </div>
          <div class="col s6 right-align">
            <span>&copy; Wisteria Lodge <span id="year"></span></span>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}
  </footer>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
  <script src="{% static 'enquiries/dist/scripts/copyright.js' %}" charset="utf-8"></script>
  <script src="{% static 'enquiries/dist/scripts/mat_init.js' %}" charset="utf-8"></script>

  {% block extra-scripts %}
  {% endblock %}
</body>
</html>

enquiries/templates/enquiries/src/enquiry-success.html
{% extends "enquiries/dist/enquiry.html" %}
{% load static %}
{% block extra-scripts %}
<script type="text/javascript" src="{% static 'enquiries/dist/scripts/toast-success.js' %}"></script>
{% endblock %}

enquiries/templates/enquiries/src/enquiry.html
{% extends "enquiries/dist/base.html" %}
{% load static %}

{% block meta-description %}
<meta name="description" content="Make an enquiry | Wisteria Lodge is a cosy yet sophisticated cottage in North-West Johannesburg, South Africa.">
{% endblock %}

{% block extra-links %}
<link rel="stylesheet" href="{% static 'enquiries/dist/stylesheets/styles.css' %}">
{% endblock %}

{% block title %}Make an Enquiry{% endblock %}

{% block nav-which-active %}
<li><a href="http://wisterialodge.co.za/">Home</a></li>
<li><a href="http://wisterialodge.co.za/enquire" class="nav-active">Enquire</a></li>
<li><a href="http://wisterialodge.co.za/contact.html">Contact Us</a></li>
{% endblock %}

{% block sidenav-which-active %}
<li><a href="http://wisterialodge.co.za/">Home</a></li>
<li><a href="http://wisterialodge.co.za/enquire" class="nav-active">Enquire</a></li>
<li><a href="http://wisterialodge.co.za/contact.html">Contact Us</a></li>
{% endblock %}

{% block main %}


  <div class="content container row">
    <div class="col s12">
      <h4>Make an Enquiry</h4>
      <p class="form-intro">Enter the details of your desired stay with us, and we'll contact you with the availability status and a relevant quote.</p>
      <p class="form-intro">Please note that stays may be a minimum of two days.</p>
    </div>


    <br>
    <br>
    <div class="col s12 form-container">
      <form class="" action="" method="post">
        {% csrf_token %}
        <div class="input-field col s12 m5">
          <label for="id_name" class="grey-text text-darken-3">Your name</label>
          {{ form.name }}
          {{ form.errors.name }}
        </div>
        <div class="input-field col s12 m5 offset-m2">
          <label for="id_email" class="grey-text text-darken-3">Your email address</label>
            {{ form.email }}
        </div>
        <div class="input-field col s12 m5">
          <label for="id_enq_date_start" class="grey-text text-darken-3">Check-in date</label>
            {{ form.enq_date_start }}
            {{ form.errors.enq_date_start }}
        </div>
        <div class="input-field col s12 m5 offset-m2">
          <label for="id_enq_date_end" class="grey-text text-darken-3">Check-out date</label>
            {{ form.enq_date_end }}
            {{ form.errors.enq_date_end }}
        </div>
        <div class="input-field col s12 m5">
            {{ form.adults }}
            <label class="grey-text text-darken-3">Number of adults</label>
        </div>
        <div class="input-field col s12 m5 offset-m2">
            {{ form.children }}
            <label class="grey-text text-darken-3">Number of children</label>
        </div>
        <div class="col s12 right-align">
          <button type="submit" name="" class="btn blue-grey darken-2 white-text">Submit</button>
        </div>
      </form>
    </div>
  </div>

{% endblock %}